# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'Speech' do

  pod 'SwiftProtobuf', git: 'https://github.com/apple/swift-protobuf.git', :tag => '0.9.24'
  pod 'SwiftGRPC', git: 'https://github.com/grpc/grpc-swift.git' #, :tag => '0.1.0'

end


