# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'Speech' do

  pod 'gRPC-Core', "~> 1.0.0-pre1.1"
  pod 'SwiftProtobuf', git: 'https://github.com/apple/swift-protobuf.git'

end


