//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: reflection.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// To build a server, implement a class that conforms to this protocol.
public protocol Reflection_ServerReflectionProvider: CallHandlerProvider {
  var interceptors: Reflection_ServerReflectionServerInterceptorFactoryProtocol? { get }

  /// The reflection service is structured as a bidirectional stream, ensuring
  /// all related requests go to a single server.
  func serverReflectionInfo(context: StreamingResponseCallContext<Reflection_ServerReflectionResponse>) -> EventLoopFuture<(StreamEvent<Reflection_ServerReflectionRequest>) -> Void>
}

extension Reflection_ServerReflectionProvider {
  public var serviceName: Substring {
    return Reflection_ServerReflectionServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "ServerReflectionInfo":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Reflection_ServerReflectionRequest>(),
        responseSerializer: ProtobufSerializer<Reflection_ServerReflectionResponse>(),
        interceptors: self.interceptors?.makeServerReflectionInfoInterceptors() ?? [],
        observerFactory: self.serverReflectionInfo(context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Reflection_ServerReflectionAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Reflection_ServerReflectionServerInterceptorFactoryProtocol? { get }

  /// The reflection service is structured as a bidirectional stream, ensuring
  /// all related requests go to a single server.
  func serverReflectionInfo(
    requestStream: GRPCAsyncRequestStream<Reflection_ServerReflectionRequest>,
    responseStream: GRPCAsyncResponseStreamWriter<Reflection_ServerReflectionResponse>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Reflection_ServerReflectionAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Reflection_ServerReflectionServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Reflection_ServerReflectionServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Reflection_ServerReflectionServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "ServerReflectionInfo":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Reflection_ServerReflectionRequest>(),
        responseSerializer: ProtobufSerializer<Reflection_ServerReflectionResponse>(),
        interceptors: self.interceptors?.makeServerReflectionInfoInterceptors() ?? [],
        wrapping: { try await self.serverReflectionInfo(requestStream: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

public protocol Reflection_ServerReflectionServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'serverReflectionInfo'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeServerReflectionInfoInterceptors() -> [ServerInterceptor<Reflection_ServerReflectionRequest, Reflection_ServerReflectionResponse>]
}

public enum Reflection_ServerReflectionServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ServerReflection",
    fullName: "reflection.ServerReflection",
    methods: [
      Reflection_ServerReflectionServerMetadata.Methods.serverReflectionInfo,
    ]
  )

  public enum Methods {
    public static let serverReflectionInfo = GRPCMethodDescriptor(
      name: "ServerReflectionInfo",
      path: "/reflection.ServerReflection/ServerReflectionInfo",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}
