#!/bin/sh
#
# Use this script to regenerate the Protocol Buffer and gRPC files
# needed to build the example.
#
# Note that it requires updated protoc, protoc-gen-swift, and
# protoc-gen-swiftgrpc binaries and assumes that protoc-gen-swift 
# is installed in $HOME/local/bin.

git clone http://github.com/googleapis/googleapis

protoc \
 	googleapis/google/datastore/v1/datastore.proto \
 	googleapis/google/datastore/v1/entity.proto \
 	googleapis/google/datastore/v1/query.proto \
	googleapis/google/type/latlng.proto \
 	-Igoogleapis \
	--swift_out=googleapis \
	--swift_opt=Visibility=Public \
	--plugin=$HOME/local/bin/protoc-gen-swift \
	--swiftgrpc_out=Sources

# move swift files to this directory
find googleapis -name "*.swift" -exec mv {} Sources \;

# remove the grpc service file; we don't need it
rm Sources/google.datastore.v1.server.pb.swift

