#!/bin/sh
#
# Use this script to regenerate the Protocol Buffer and gRPC files
# needed to build the example.
#
# Note that it requires updated protoc, protoc-gen-swift, and
# protoc-gen-grpc-swift binaries and assumes that protoc-gen-swift
# is installed in $HOME/local/bin.

if [ ! -d "googleapis" ]; then
  curl -L -O https://github.com/googleapis/googleapis/archive/master.zip
  unzip master.zip
  rm -f master.zip
  mv googleapis-master googleapis
fi

protoc \
	google/spanner/v1/keys.proto \
	google/spanner/v1/mutation.proto \
	google/spanner/v1/query_plan.proto \
	google/spanner/v1/result_set.proto \
	google/spanner/v1/spanner.proto \
	google/spanner/v1/transaction.proto \
	google/spanner/v1/type.proto \
	google/spanner/admin/instance/v1/spanner_instance_admin.proto \
	google/spanner/admin/database/v1/spanner_database_admin.proto \
	google/longrunning/operations.proto \
	google/rpc/status.proto \
	google/iam/v1/iam_policy.proto \
	google/iam/v1/policy.proto \
 	-Igoogleapis \
	--swift_out=googleapis \
	--grpc-swift_out=googleapis

# move Swift files to the Sources directory
find googleapis -name "*.swift" -exec mv {} Sources \;
