name: PR

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "gRPC"

  grpc-soundness:
    name: Soundness
    uses: ./.github/workflows/soundness.yml

  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:
      linux_5_9_enabled: false
      linux_5_10_enabled: false
      linux_6_0_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_6_1_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"

  construct-examples-matrix:
    name: Construct Examples matrix
    runs-on: ubuntu-latest
    outputs:
      examples-matrix: '${{ steps.generate-matrix.outputs.examples-matrix }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - id: generate-matrix
        run: echo "examples-matrix=$(curl -s https://raw.githubusercontent.com/apple/swift-nio/main/scripts/generate_matrix.sh | bash)" >> "$GITHUB_OUTPUT"
        env:
          MATRIX_LINUX_5_9_ENABLED: false
          MATRIX_LINUX_5_10_ENABLED: false
          MATRIX_LINUX_COMMAND: "./dev/build-examples.sh"
          MATRIX_LINUX_SETUP_COMMAND: "apt update && apt install -y protobuf-compiler"

  examples-matrix:
    name: Examples
    needs: construct-examples-matrix
    uses: apple/swift-nio/.github/workflows/swift_test_matrix.yml@main
    with:
      name: "Examples"
      matrix_string: '${{ needs.construct-examples-matrix.outputs.examples-matrix }}'

  benchmarks:
    name: Benchmarks
    uses: apple/swift-nio/.github/workflows/benchmarks.yml@main
    with:
      benchmark_package_path: "IntegrationTests/Benchmarks"
      linux_5_9_enabled: false
      linux_5_10_enabled: false

  cxx-interop:
    name: Cxx interop
    uses: apple/swift-nio/.github/workflows/cxx_interop.yml@main
    with:
      linux_5_9_enabled: false
      linux_5_10_enabled: false
